export enum UserActivityType {
  LOGIN = 'LOGIN',
  SIGNUP = 'SIGNUP',
  LOGOUT = 'LOGOUT',
  USERNAME_CHANGE = 'USERNAME_CHANGE',
  ACCOUNT_DEACTIVATION = 'ACCOUNT_DEACTIVATION',
  OAUTH_LINK = 'OAUTH_LINK',
  OAUTH_UNLINK = 'OAUTH_UNLINK',
}
