import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { checkAuth } from '@/lib/api';

const AboutPage = () => {
  const appName = import.meta.env.APP_NAME || 'Mailhub';
  const isLoggedIn = checkAuth();

  return (
    <div className="flex min-h-screen flex-col">
      <Header isLoggedIn={isLoggedIn} />

      <main className="flex flex-1 flex-col px-4 py-16">
        <div className="container mx-auto max-w-3xl">
          <div className="text-center mb-14">
            <h1 className="text-4xl font-bold mb-3">Why We Built {appName}</h1>
            <p className="text-lg text-muted-foreground">
              Protecting your email starts with protecting your identity
            </p>
          </div>

          <div className="rounded-2xl bg-gradient-to-br from-primary/5 via-background to-primary/10 border p-8 md:p-12">
            <div className="space-y-6 text-muted-foreground leading-relaxed">
              <p>
                We created {appName} after seeing how often personal data gets exposed online.
                Because email addresses act as powerful identifiers that connect information across
                services, we built {appName} to help you protect yours.
              </p>

              <p>
                {appName} keeps your real email address private. Instead of sharing your primary
                email with websites you don't fully trust, you can use{' '}
                <span className="font-medium text-foreground">private addresses</span> generated by{' '}
                {appName} and manage everything from a single place.
              </p>

              <p>
                The best way to protect your identity online is to use a different email for every
                service. That's why {appName} lets you create up to{' '}
                <span className="font-medium text-foreground">
                  20 private email addresses for free
                </span>
                . Even if a service experiences a data breach, your identity cannot easily be linked
                through a single email address.
              </p>

              <p>
                Your email address is encrypted before it is stored. We use{' '}
                <span className="font-medium text-foreground">AES-256 and SHA-256</span> encryption
                from the client to the server, ensuring that no one — not even with database
                access — can identify who uses which email address. Our entire codebase is open on
                GitHub so you can see exactly how your data is handled.
              </p>

              <p>
                {appName} is fully open source and always will be. We chose the{' '}
                <span className="font-medium text-foreground">AGPL-3.0</span> license to guarantee
                openness wherever {appName}'s code is used.
              </p>

              <p className="font-medium text-foreground">
                Our goal is simple: help keep your personal information safe.
              </p>
            </div>
          </div>

          <div className="mt-10 p-6 rounded-lg bg-muted/30 border">
            <h3 className="font-semibold mb-3 text-center">Privacy and Transparency</h3>
            <p className="text-sm text-muted-foreground text-center">
              No data collection, no data sales. <br />
              Only encrypted email address are stored, and every line of code is open-source on
              Github, licensed under AGPL-3.0. <br />
              Visit our{' '}
              <a
                href="https://github.com/youngjinmo/private-mailhub"
                target="_blank"
                rel="noopener noreferrer"
                className="underline text-primary hover:text-foreground transition-colors"
              >
                open-source repository
              </a>
            </p>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
};

export default AboutPage;
